FROM python:3.9-slim-buster

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y curl git

RUN python -m pip install pip==24.0

WORKDIR /docker
COPY ./docker/flask/entrypoint.sh .
RUN chmod +x ./entrypoint.sh

WORKDIR /requirements
COPY ./igvf-catalog-llm/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /igvf-catalog-llm
COPY . .

WORKDIR /igvf-catalog-llm/igvf-catalog-llm

EXPOSE 5000

ENV FLASK_ENV=production
ENV FLASK_DEBUG=0

ENTRYPOINT ["/docker/entrypoint.sh"]

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
