FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y curl git

RUN python -m pip install pip==26.0.1

WORKDIR /docker
COPY ./docker/flask/entrypoint.sh .
RUN chmod +x ./entrypoint.sh

WORKDIR /requirements
COPY ./igvf-catalog-llm/requirements.txt .
COPY ./igvf-catalog-llm/build-constraint.txt .
RUN PIP_BUILD_CONSTRAINT=./build-constraint.txt pip --use-feature=build-constraint install --no-cache-dir -r requirements.txt

WORKDIR /igvf-catalog-llm
COPY . .

WORKDIR /igvf-catalog-llm/igvf-catalog-llm

EXPOSE 5000

ENV FLASK_ENV=production
ENV FLASK_DEBUG=0

ENTRYPOINT ["/docker/entrypoint.sh"]

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
